package com.blockdisplay.plugin;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.core.Filter;
import org.apache.logging.log4j.core.LogEvent;
import org.apache.logging.log4j.core.Logger;
import org.apache.logging.log4j.core.filter.AbstractFilter;
import org.apache.logging.log4j.message.Message;

/**
 * Log4j2 filter that suppresses the "Modified entity data of ..." and
 * "Nothing changed..." console messages generated by /data merge commands
 * dispatched by our animation and spawn systems.
 *
 * This filter is registered on the root logger in onEnable() and removed in onDisable().
 */
public class CommandFeedbackFilter extends AbstractFilter {

    private static final String[] SUPPRESSED_MESSAGES = {
            "Modified entity data of",
            "Nothing changed. The specified properties already have these values",
            "No entity was found",
            "Summoned new"
    };

    @Override
    public Result filter(LogEvent event) {
        Message msg = event.getMessage();
        if (msg != null) {
            String formatted = msg.getFormattedMessage();
            if (formatted != null) {
                for (String suppressed : SUPPRESSED_MESSAGES) {
                    if (formatted.contains(suppressed)) {
                        return Result.DENY;
                    }
                }
            }
        }
        return Result.NEUTRAL;
    }

    @Override
    public Result filter(Logger logger, Level level, Marker marker, String msg, Object... params) {
        if (msg != null) {
            for (String suppressed : SUPPRESSED_MESSAGES) {
                if (msg.contains(suppressed)) {
                    return Result.DENY;
                }
            }
        }
        return Result.NEUTRAL;
    }

    @Override
    public Result filter(Logger logger, Level level, Marker marker, Object msg, Throwable t) {
        if (msg != null) {
            String str = msg.toString();
            for (String suppressed : SUPPRESSED_MESSAGES) {
                if (str.contains(suppressed)) {
                    return Result.DENY;
                }
            }
        }
        return Result.NEUTRAL;
    }

    @Override
    public Result filter(Logger logger, Level level, Marker marker, Message msg, Throwable t) {
        if (msg != null) {
            String formatted = msg.getFormattedMessage();
            if (formatted != null) {
                for (String suppressed : SUPPRESSED_MESSAGES) {
                    if (formatted.contains(suppressed)) {
                        return Result.DENY;
                    }
                }
            }
        }
        return Result.NEUTRAL;
    }
}
